# Generated by Django 5.2.8 on 2026-01-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='instrumento',
        ),
        migrations.AddField(
            model_name='escala',
            name='instrumento',
            field=models.ManyToManyField(blank=True, related_name='instrumento_da_escala', to='escala.instrumento'),
        ),
    ]
